### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by bdronneau** [basti1dr/imwatchingyou#49]
https://developers.google.com/api-client-library/ruby/start/installation

**Comment by bdronneau** [comment]
- http://stackoverflow.com/a/19240277/4809513
- https://github.com/google/google-api-ruby-client-samples/tree/master/service_account
- https://www.slatestudio.com/blog/p/how-to-pull-google-analytics-data-from-rails-app
- https://developers.google.com/analytics/devguides/reporting/core/v3/#started

**Comment by basti1dr** [comment]
https://www.slatestudio.com/blog/p/how-to-pull-google-analytics-data-from-rails-app

**Comment by basti1dr** [comment]
https://developers.google.com/analytics/devguides/reporting/core/v3/#started
