### ISSUE TITLE
Add "box" for the local dev. environment

### ISSUE THREAD

**Issue by eilgin** [basti1dr/imwatchingyou#72]
To ease development and testing on a local machine, it would be nice to have a way to build the platform which will contains all the project dependencies (ruby, gemfile, etc) using _standard_ virt. program like `vagrant`. What do you think ? Maybe you have some suggestions on the things to integrate (the minimum should replicate the `travis` env.) ?

I can make the `Vagrantfile` and do a PR if that suits you.

**Comment by bdronneau** [comment]
Yes you can (:
Debian 8 , rvm, bundler sound a good start.
